apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 361848949410.dkr.ecr.ap-northeast-2.amazonaws.com/spring-demo
  newTag: a4fb0198
- name: 942083365966.dkr.ecr.ap-northeast-2.amazonaws.com/spring-demo
  newTag: 7551aa70
resources:
- ../../base
